name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python pdf_to_image.py input.pdf output.png
import argparse
import fitz

def pdf_to_image(pdf_path, output_path):
    """
    将单页 PDF 转换为图片
    :param pdf_path: PDF 文件的路径
    :param output_path: 输出图片的路径
    """
    try:
        # 打开 PDF 文件
        pdf_document = fitz.open(pdf_path)
        if len(pdf_document) != 1:
            raise ValueError("仅支持单页 PDF 文件。")
        # 获取第一页
        page = pdf_document[0]
        # 设置缩放比例以提高图片清晰度
        zoom_x = 2.0
        zoom_y = 2.0
        mat = fitz.Matrix(zoom_x, zoom_y)
        pix = page.get_pixmap(matrix=mat)
        # 保存图片
        pix.save(output_path)
        pdf_document.close()
        print(f"PDF 已成功转换为图片，保存路径为: {output_path}")
    except Exception as e:
        print(f"转换过程中出现错误: {e}")
    pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="将单页 PDF 转换为图片")
    parser.add_argument("pdf_path", help="输入的 PDF 文件路径")
    parser.add_argument("output_path", help="输出的图片文件路径")
    args = parser.parse_args()
    pdf_to_image(args.pdf_path, args.output_path)
